# Builds and tests the geas frontend
name: Kube Fledged Helm Chart Build

# Trigger the workflow only on pushes to the main branch
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  helm-publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Run chart-releaser (only on pushes)
        if: ${{ github.event_name == 'push' }}
        uses: helm/chart-releaser-action@v1.2.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

        with:
          charts_dir: deploy/kubefledged-operator/helm-charts
